spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"

server:
  port: 8080

zuul:
  routes:
    product-manager:
      path: "/**/products**"
      strip-prefix: false
    customer-manager:
      path: "/customers**"
      strip-prefix: false

eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance
